DeliverIT.Web/Controllers/ParcelController.cs
using DeliverIT.Models.RequestModels;
using DeliverIT.Services.Interfaces;
using DeliverIT.Services.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DeliverIT.Web.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]    
    public class ParcelController : Controller
    {
        private readonly IParcelService _parcelServices;

        public ParcelController(IParcelService parcelServices)
        {
            _parcelServices = parcelServices;
        }
        [HttpPost]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Create([FromBody] CreateParcelRequestModel requestModel)
        {
            var response = await _parcelServices.CreateParcelAsync(requestModel);
            return Json(response);
        }
        [HttpPut]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Update([FromQuery] UpdateParcelRequestModel requestModel)
        {
            var response = await _parcelServices.UpdateParcelAsync(requestModel);
            return Json(response);
        }

        [HttpDelete]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Delete(DeleteParcelRequestModel requestModel)
        {
            var result = await _parcelServices.DeleteParcelAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Get([FromQuery] FilterParcelRequesteModel requestModel)
        {
            var response = await _parcelServices.FilterParcelAsync(requestModel);
            return Json(response);
        }
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> CreateParcel()
        {
            return View(new CreateParcelRequestModel());
        }
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> ShowParcels()
        {
            return View();
        }

        [HttpPost]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> GetParcels(GetPaginatedRequestModel requestModel)
        {
            var request = new GetParcelsRequestModel
            {
                Skip = requestModel.Skip,
                Take = requestModel.Take,
                UserRole = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.Role)?.Value,
                UserId = long.Parse(User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value)
            };           

            var result = await _parcelServices.GetParcelAsync(request);
            if (result.IsSuccess)
            {
                return Json(result);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> EditParcel([FromQuery] EditParcelRequestModel requestModel)
        {
            var result = await _parcelServices.GetParcelByIdAsync(requestModel);
            return View(result);
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> ShowCustomerParcels()
        {
            return View("ShowCustomerParcels");
        }
    }
}

        //[HttpPost]
        //public async Task<IActionResult> UpdateParcel([FromForm] UpdateParcelRequestModel requestModel)
        //{
        //    var result = await _parcelServices.UpdateParcelAsync(requestModel);
        //    if (result.IsSuccess)
        //    {
        //        return RedirectToAction("ShowParcels");
        //    }
        //    return BadRequest(result.Message);
        //}
        //[HttpGet]
        //public async Task<IActionResult> ShowParcelMvc()
        //{
        //    return View();
        //}

DeliverIT.Web/Controllers/ShipmentController.cs
using DeliverIT.Models.RequestModels;
using DeliverIT.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DeliverIT.Web.Controllers
{
    [Route("/api/[controller]/[action]")]
    [ApiController]
    [Authorize(Roles = "Employee, Admin")]
    public class ShipmentController : Controller
    {
        private readonly IShipmentService _shipmentServices;

        public ShipmentController(IShipmentService shipmentServices)
        {
            _shipmentServices = shipmentServices;
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> ShowShipments()
        {
            return View();
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> ShowShipmentsMvc()
        {
            return View();
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> CreateShipment()
        {
            return View(new CreateShipmentRequestModel());
        }       

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateShipmentRequestModel requestModel)
        {
            var result = await _shipmentServices.CreateShipmentAsync(requestModel);
           
            if (result.IsSuccess)
            {
                //return View("CreateShipment");
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> EditShipment([FromQuery] EditShipmentRequestModel requestModel)
        {
            var result = await _shipmentServices.GetShipmentByIdAsync(requestModel);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateShipment([FromForm] UpdateShipmentRequestModel requestModel)
        {
            var result = await _shipmentServices.UpdateShipmentAsync(requestModel);
            if (result.IsSuccess)
            {
                return RedirectToAction("ShowShipments");                
            }
            return BadRequest(result.Message);
        }
        [HttpPut]
        public async Task<IActionResult> Update([FromBody] UpdateShipmentRequestModel requestModel)
        {
            var result = await _shipmentServices.UpdateShipmentAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        public async Task<IActionResult> GetShipmentsByWarehouseOrigin([FromQuery] GetShipmentsByWarehouseRequestModel requestModel)
        {
            var result = await _shipmentServices.GetShipmentByOriginWarehouseAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        // TODO : Filtration by Next arriving Shipment - Next arriving Bool -> Show all shipments if false / Show only next arriving if ture
        public async Task<IActionResult> GetShipmentsByWarehouseDestination([FromQuery] GetShipmentsByWarehouseRequestModel requestModel)
        {
            var result = await _shipmentServices.GetShipmentByDestinationWarehouseAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        public async Task<IActionResult> GetShipmentsByCustomer([FromQuery] GetShipmentsByCustomerRequestModel requestModel)
        {
            var result = await _shipmentServices.GetShipmentByCustomerAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        [HttpPost]
        public async Task<IActionResult> GetShipments(GetPaginatedRequestModel requestModel)
        {
            var result = await _shipmentServices.GetShipmentAsync(requestModel);
            if (result.IsSuccess)
            {
                return Json(result);
            }
            return BadRequest(result.Message);
        }       

        [HttpDelete]
        public async Task<IActionResult> Delete(DeleteShipmentRequestModel requestModel)
        {
            var result = await _shipmentServices.DeleteShipmentAsync(requestModel);
            if (result.IsSuccess)
            {
                return Ok(result.Message);
            }
            return BadRequest(result.Message);
        }

        //[HttpPost]
        //[ApiExplorerSettings(IgnoreApi = true)]
        //public async Task<IActionResult> GetShipmentsMvc(GetPaginatedRequestModel requestModel)
        //{
        //    var result = await _shipmentServices.GetShipmentAsync(requestModel);
        //    return PartialView("_ShipmentsTablePartial", result);
        //}

        //[HttpPost]
        //[ApiExplorerSettings(IgnoreApi = true)]
        //public async Task<IActionResult> DeleteMvc([FromForm] DeleteShipmentRequestModel requestModel)
        //{
        //    var result = await _shipmentServices.DeleteShipmentAsync(requestModel);
        //    if (result.IsSuccess)
        //    {
        //        return RedirectToAction("ShowShipmentsMvc");
        //    }
        //    return BadRequest(result.Message);
        //}
    }
}

DeliverIT.Web/Views/Shared/_Layout-Old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-alpine-dark.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TestProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>

DeliverIT.Web/Views/Shared/_ParcelsTable.cshtml
<section class="centered-container">
    <div class="inner-centered-container">
        <h2 class="text-white-c">Parcels List</h2>

        <div id="myGrid" class="ag-theme-alpine-dark"></div>

        <div id="pagination-container">
            <button id="prev-button" disabled class="btn pageing-buttons text-white-c">PREVIOUS PAGE</button>
            <h3 id="page-counter">Page: 1</h3>
            <button id="next-button" class="btn pageing-buttons text-white-c">NEXT PAGE</button>
        </div>
    </div>

</section></section>

DeliverIT.Web/Views/Shared/_ParcelsTablePartial.cshtml
@model DeliverIT.Models.ResponseModels.GetParcelsResponse

<table id="table2" class="styled-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Weight</th>
                <th>Delivery To Address</th>
                <th>Customer ID</th>
                <th>Warehouse ID</th>
                <th>Category Name</th>
                <th>Shipment ID</th>
                <th>Arrival Date</th>
                <th>EDIT ACTION</th>
                <th>DELETE ACTION</th>
            </tr>
        </thead>
        <tbody id="tbody2">
            @foreach (var item in Model.Data)
            {
            <tr>
                <td>@item.Id</td>
                <td>@item.Weight</td>
                <td>@item.DeliveryToAddress</td>
                <td>@item.CustomerId</td>
                <td>@item.WarehouseId</td>
                <td>@item.CategoryName</td>
                <td>@item.ShipmentId</td>
                <td>@item.ArrivalDate</td>
                <td class="button-container">
                    <a type="button" class="mvc-edit-button edit-shipment-button" href="/api/Parcel/EditParcel?id=@item.Id">Edit</a>
                </td>
                <td>
                    <form asp-controller="Parcel" asp-action="DeleteMvc">
                        <input type="hidden" name="Id" value="@item.Id" />
                        <button class="mvc-delete-button" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            }
        </tbody>        
</table>

<div>
    <div id="pagination-container">
        @if (Model.CurrentPage == 1)
        {
            <button id="prev-button" disabled class="btn pageing-buttons">PREVIOUS PAGE</button>
        }
        else
        {
            <button id="prev-button" class="btn pageing-buttons">PREVIOUS PAGE</button>
        }

        <h3 id="page-counter">@Model.CurrentPage</h3>

        @if (Model.IsLastPage)
        {
            <button id="next-button" disabled class="btn pageing-buttons">NEXT PAGE</button>
        }
        else
        {
            <button id="next-button" class="btn pageing-buttons">NEXT PAGE</button>
        }
    </div>
</div>

DeliverIT.Web/Views/Shared/_ShipmentsTable.cshtml
<section class="centered-container">
    <div class="inner-centered-container">
        <h2 class="text-white-c">Shipments List</h2>

        <div id="myGrid" class="ag-theme-alpine-dark"></div>

        <div id="pagination-container">
            <button id="prev-button" disabled class="btn pageing-buttons text-white-c">PREVIOUS PAGE</button>
            <h3 id="page-counter">Page: 1</h3>
            <button id="next-button" class="btn pageing-buttons text-white-c">NEXT PAGE</button>
        </div>
    </div>

</section>

DeliverIT.Web/Views/Shared/_ShipmentsTablePartial.cshtml
@model DeliverIT.Models.ResponseModels.GetShipmentsResponse

<table id="table1" class="styled-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Status Name</th>
                <th>Arrival Time</th>
                <th>Departure Time</th>
                <th>Destination Warehouse</th>
                <th>Origin Warehouse</th>
                <th>EDIT ACTION</th>
                <th>DELETE ACTION</th>
            </tr>
        </thead>
        <tbody id="tbody1">
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.StatusName</td>
                    <td>@item.ArrivalTime</td>
                    <td>@item.DepartureTime</td>
                    <td>@item.DestinationWarehouse</td>
                    <td>@item.OriginWarehouse</td>
                    <td class="button-container">
                        <a type="button" class="mvc-edit-button edit-shipment-button" href="/api/Shipment/EditShipment?id=@item.Id">Edit</a>
                    </td>
                    <td>
                        <form asp-controller="Shipment" asp-action="DeleteMvc">
                            <input type="hidden" name="Id" value="@item.Id" />
                            <button class="mvc-delete-button" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>        
</table>

<div>
    <div id="pagination-container">
        @if (Model.CurrentPage == 1)
        {
            <button id="prev-button" disabled class="btn pageing-buttons">PREVIOUS PAGE</button>
        }
        else
        {
            <button id="prev-button" class="btn pageing-buttons">PREVIOUS PAGE</button>
        }

        <h3 id="page-counter">@Model.CurrentPage</h3>

        @if (Model.IsLastPage)
        {
            <button id="next-button" disabled class="btn pageing-buttons">NEXT PAGE</button>
        }
        else
        {
            <button id="next-button" class="btn pageing-buttons">NEXT PAGE</button>
        }
    </div>
</div>